### ISSUE TITLE
Errors in the code

### ISSUE THREAD

**Issue by sidney1994** [ramakanth-pasunuru/CAS-MAS#2]
There are some errors in your code. such as https://github.com/ramakanth-pasunuru/CAS-MAS/blob/3e2164ca273a5510d342e8f58a85557c3f5ca77a/models/rte_classifier.py#L196 https://github.com/ramakanth-pasunuru/CAS-MAS/blob/3e2164ca273a5510d342e8f58a85557c3f5ca77a/trainer.py#L938

**Comment by ramakanth-pasunuru** [comment]
thanks for pointing. I cleaned the code
